### ISSUE TITLE
Suggestions on improving RSS parsing

### ISSUE THREAD

**Issue by kristapsk** [piraces/rsslay#14]
Made recently Nostr feed for Stacker News, but there are things that could be improved, see https://stacker.news/items/130825.

In Stacker News you often have two URLs, one for linked article or whatever, another for Stacker News discussion page. That second one is in two places - HTML encoded at `<description>` where HTML is stripped for Nostr (which is correct behaviour) and `<comments>` tag, which is ignored by rsslay. RSS address - https://stacker.news/rss.

Another issue which I noticed with https://kursors.lv/feed/ is that `&#nnnn;` HTML entities are not parsed and converted to UTF-8.

Here are differences between Nostr feed by rsslay on Damus and unofficial Twitter feed (of course, they shouldn't match perfectly, but just to get idea what would look nicer):
![image](https://user-images.githubusercontent.com/4500994/216767604-6efa74ca-eeb8-4207-8739-d34d4fd162e8.png) 
![image](https://user-images.githubusercontent.com/4500994/216767613-30b0d7aa-4fa5-40b9-92df-e7cae1ed101f.png)

**Comment by piraces** [comment]
First of all thank you for reporting this case! I have opened the issue on the official repo of the library I use for parsing the feeds (since it does not have support to extract that `comments` tag): https://github.com/mmcdole/gofeed/issues/198

 With this actual feed for stacker.news, I will append the comments URL from the `guid` entry as it is the same (temporal). So it appears as similar as possible of the twitter one.

For the other case I'll review it in detail.

**Comment by kristapsk** [comment]
> For the other case I'll review it in detail.

For HTML entity decoding the same applies to https://kripto.media/feed/. I think it's generic issue with WordPress.

**Comment by piraces** [comment]
I just checked with latest version and now comments appear as expected in stacker.news profile and html encondings problem are solved as well... You may see some duplicated entries due to previous events already propagated to other relays, but we can do nothing about it 😞 

If you see problems again please comment on this issue. I will keep it open to keep track for the upstream issue: https://github.com/mmcdole/gofeed/issues/198

**Comment by piraces** [comment]
Now supporting comments from RSS feeds! For example: stacker.news and Wordpress sites!

Related commit: https://github.com/piraces/rsslay/commit/4f377ced349995bb255a8c13096987434a3ca0c6
