### ISSUE TITLE
In clients that support url previews, rsslay notes take a while before the preview eventually gets rendered

### ISSUE THREAD

**Issue by ghobs91** [piraces/rsslay#38]

**Comment by ghobs91** [comment]
It's when the client tries to load the url preview image of the nitter.moomoo.me url (if the twitter post has an image to preview). It can take a while before the image finally shows, no matter which client it is.

**Comment by ghobs91** [comment]
Example, try loading this profile: https://snort.social/p/npub1acsdz8eg3qwyleen3g8fje5s7kgshaqp62yp0tl6mqcv5czpvznq8wc5sx

**Comment by piraces** [comment]
Thanks for the example! Will look into it! 🤙

**Comment by piraces** [comment]
Will continue to monitor this, but seems unrelated to the current implementation of rsslay... It's depending on the load of `nitter.moomoo.me` in this case (or the feed page in other cases).

Nevertheless, it seems to be working better since for example snort.social don't load images directly unless you allow it... so less load.

**Comment by ghobs91** [comment]
Now that Snort has link previews, I don't see this issue with rsslay.nostr.moe profiles anymore!

**Comment by piraces** [comment]
Awesome!! Thanks for letting me know 👍
